<?php

namespace Modules\Cases\Models;

use Illuminate\Database\Eloquent\Model;

class CrmCase extends Model
{
    protected $table = 'crm_case';

    protected $fillable = [
        'case_title',
        'case_name',
        'case_firstname',
        'case_lastname',
        'case_adres',
        'case_city',
        'case_city_deal',
        'case_area',
        'case_postcode',
        'case_county',
        'case_trader_id',
        'case_source_from',
        'case_supervisor_id',
        'case_customer_id',
        'case_author_id',
        'case_source',
        'case_phone',
        'case_email',
        'case_machine_type',
        'case_brand',
        'case_model',
        'case_nrseria',
        'case_amount',
        'case_amount_ams',
        'case_re_contact_date',
        'case_re_contact_date_real',
        'case_re_contact_date_cron',
        'case_status',
        'case_aditional',
        'case_aneks',
        'case_lead',
        'case_offer',
        'case_win',
        'case_adddate',
        'case_expiration_data',
        'case_file_id',
        'case_file_umowa_id',
        'case_adv_id',
        'case_adv_data',
        'case_data_fv',
        'case_deal_date',
        'case_nrfv',
        'case_amount_purchase',
        'case_service_assignments',
        'case_rwmr',
        'case_summary_description',
        'case_premium_group',
        'case_rw',
        'case_ams',
        'case_prepared',
        'case_amount_prepared',
        'case_serwis_nr',
        'case_description',
        'case_price_other',
        'case_correction_description',
        'case_correction_amount',
        'case_total_cost',
        'case_margin',
        'case_correction_margin',
        'case_group',
        'case_trader_bonus',
        'case_manager_bonus',
        'case_margin_percent',
        'case_deadline_days',
        'case_interest',
        'case_interest_amount',
        'case_complete_documentation',
        'case_trader_bonus_pln',
        'case_menager_bonus_pln',
        'case_price_netto',
        'case_price_brutto',
        'case_currency',
        'case_nip',
        'case_zadatek',
        'case_deal_termin',
        'case_status_deal',
        'case_warranty_start',
        'case_warranty_end',
        'case_gen_spec',
        'case_gen_additional',
        'case_gen_additional_info',
        'case_magazyn_type',
        'case_zadatek_switch',
        'case_aneks_switch',
        'case_foto_switch',
        'case_change_data_switch',
        'case_open_flag',
        'case_created_at',
        'case_update_at',
    ];

    public $timestamps = false;
}
